query KnotById($id: ItemId!) {
  knot(filter: { id: { eq: $id } }) {
    id
    name
    description
    history
    uses
    isbasic
    linkedKnots {
      links {
        id
        name
      }
    }
    gif {
      url
    }
  }
}
