query knotById($id: ItemId!) {
  knot(filter: { id: { eq: $id } }) {
    id
    name
    isbasic
    gif {
      url
    }
    knotData {
      description
      history
      uses
      linkedKnots {
        links {
          id
          name
        }
      }
    }
  }
}
